<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "notification".
 *
 * @property integer $id
 * @property string $type
 * @property string $params
 * @property boolean $is_active
 * @property string $created_at
 * @property integer $recipient_id
 * @property integer $reference_id
 *
 * @property \common\models\SteamUser $recipient
 * @property string $aliasModel
 */
abstract class Notification extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'notification';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['type', 'params', 'recipient_id'], 'required'],
            [['type', 'params'], 'string'],
            [['is_active'], 'boolean'],
            [['created_at'], 'safe'],
            [['recipient_id', 'reference_id'], 'integer'],
            [['recipient_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\SteamUser::className(), 'targetAttribute' => ['recipient_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'type' => Yii::t('app', 'Type'),
            'params' => Yii::t('app', 'Params'),
            'is_active' => Yii::t('app', 'Is Active'),
            'created_at' => Yii::t('app', 'Created At'),
            'recipient_id' => Yii::t('app', 'Recipient ID'),
            'reference_id' => Yii::t('app', 'Reference ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRecipient()
    {
        return $this->hasOne(\common\models\SteamUser::className(), ['id' => 'recipient_id']);
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\NotificationQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\NotificationQuery(get_called_class());
    }


}
